### ISSUE TITLE
Is it true that transformers have one attention layer throughout the paper?

### ISSUE THREAD

**Issue by chocolates** [null-xyj/CoBFormer#1]
Hi, thanks for this very impressive and interesting paper.

I just have a question that **is it true that you consider 1 attention layer in the graph transformers throughout the paper?** 

Specifically, **in Sec.3 where you analyze the Over-Globalizing Problem, do you always assume the case that transformers have one attention layer**?

It would be great if you can clarify this point. And thanks in advance for your time.

**Comment by null-xyj** [comment]
> Hi, thanks for this very impressive and interesting paper.
> 
> I just have a question that **is it true that you consider 1 attention layer in the graph transformers throughout the paper?**
> 
> Specifically, **in Sec.3 where you analyze the Over-Globalizing Problem, do you always assume the case that transformers have one attention layer**?
> 
> It would be great if you can clarify this point. And thanks in advance for your time.

Thank you for your attention to our work and the positive evaluation you've given it. The question you've raised is insightful, and we're pleased to address it and provide clarity. It's important to clarify that we do not assume Graph Transformers are limited to a single attention layer. For instance, in Figure 1, we present a visualization of the Attn-k for NodeFormer, which is a Graph Transformer that incorporates multiple attention heads and layers. To achieve this visualization, we take the average attention score across each head and plot the results for the first layer (In fact, the visualization of each layer will exhibit the similar trend). In order to theoretically analyze the Over-Globalizing Problem, we assume that Graph Transformers should be capable of learning a graph structure that ensures the smoothness of embeddings/features/labels.  Ideally, each layer of a Graph Transformer should strive to meet this assumption. 

It is worth noting that our research is primarily focused on node-level tasks. While we do not assume that Graph Transformers only have one attention layer, but in the actual scenario, we usually adopt only few Graph Transformer layers considering the huge scale of networks and the high complexity of  Graph Transformers. Furthermore, SGFormer[1] has argued that a single global attention layer is sufficient to achieve optimal expressive power for node classification tasks.

We appreciate the value of your question and are grateful for the opportunity to further clarify our work.

[1] Qitian Wu, et al. "Simplifying and Empowering Transformers for Large-Graph Representations", NeurIPS (2023)

**Comment by chocolates** [comment]
> For instance, in Figure 1, we present a visualization of the Attn-k for NodeFormer, which is a Graph Transformer that incorporates multiple attention heads and layers. 

> To achieve this visualization, we take the average attention score across each head and plot the results for the first layer

> (In fact, the visualization of each layer will exhibit the similar trend)

> In order to theoretically analyze the Over-Globalizing Problem... Ideally, each layer of a Graph Transformer should strive to meet this assumption.


Thanks a lot for the clarification. I understand Fig1.b,c now.

> we usually adopt only few Graph Transformer layers considering the huge scale of networks and the high complexity of Graph Transformers. Furthermore, SGFormer[1] has argued that a single global attention layer is sufficient to achieve optimal expressive power for node classification tasks.

Thanks for sharing this information too!
